// SPDX-License-Identifier: MIT
// Bundle assembly. Pure: it takes the project's files as bytes and returns the finished container
// bytes. The CLI supplies the filesystem; nothing here touches one, so a server could assemble a
// bundle from an upload with the same code.

import { canonicalJson } from "./canonical-json.js";
import { writeContainer } from "./container.js";
import { fileHash, hashesUnder, computeIntegrity, jsonHash, HASH_ALGORITHM } from "./hashes.js";
import { utf8, fromUtf8 } from "./sha256.js";
import { safeJsonParse } from "./canonical-json.js";
import { LIMITS } from "./limits.js";
import { SCHEMA_VERSION, CREATOR_KIT_VERSION, RUNTIME_VERSION, PROTOCOL_RELEASE_COMPATIBILITY } from "./version.js";

export class BuildError extends Error {}

/** Paths the builder owns; a project directory must not supply them. */
export const GENERATED_ENTRIES = Object.freeze(["relics.project.json", "checksums.json"]);

/**
 * Deterministic, human-readable JSON text: keys sorted at every level, two-space indent, one
 * trailing newline. Byte-stable across engines, so a file hash of this text is reproducible.
 * @param {unknown} value
 */
export function stableJsonText(value) {
  return `${JSON.stringify(sortDeep(value), null, 2)}\n`;
}

function sortDeep(value) {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value && typeof value === "object") {
    /** @type {Record<string, unknown>} */
    const out = {};
    for (const key of Object.keys(value).sort()) {
      if (value[key] === undefined) continue;
      out[key] = sortDeep(value[key]);
    }
    return out;
  }
  return value;
}

/**
 * @param {{
 *   files: Map<string, Uint8Array>,
 *   config: Record<string, unknown>,
 * }} input `files` holds every bundle entry except the two generated ones; `config` is the
 *   creator's project configuration (the manifest without its hashes and integrity block).
 * @returns {{ bytes: Uint8Array, manifest: any, checksums: any, entries: Map<string, Uint8Array> }}
 */
export function assembleBundle({ files, config }) {
  if (!(files instanceof Map)) throw new BuildError("files must be a Map of path -> bytes");
  for (const generated of GENERATED_ENTRIES) {
    if (files.has(generated)) throw new BuildError(`${generated} is generated by the builder; remove it from the project directory`);
  }
  if (!files.has("generator/generate.js")) throw new BuildError("generator/generate.js is required");
  for (const required of ["traits/schema.json", "market/mappings.json", "metadata/collection.json"]) {
    if (!files.has(required)) throw new BuildError(`${required} is required`);
  }

  const scriptBytes = files.get("generator/generate.js");
  if (scriptBytes.length > LIMITS.maxScriptBytes) {
    throw new BuildError(`generator/generate.js is ${scriptBytes.length} bytes; the public script budget is ${LIMITS.maxScriptBytes}`);
  }

  const dependencies = hashesUnder(files, "generator/");
  const media = hashesUnder(files, "assets/");
  const traitSchema = parseJsonEntry(files, "traits/schema.json");
  const marketMappings = parseJsonEntry(files, "market/mappings.json");
  const collectionMetadata = parseJsonEntry(files, "metadata/collection.json");

  const manifestWithoutIntegrity = {
    schemaVersion: SCHEMA_VERSION,
    creatorKitVersion: CREATOR_KIT_VERSION,
    runtimeVersion: RUNTIME_VERSION,
    protocolReleaseCompatibility: PROTOCOL_RELEASE_COMPATIBILITY,
    ...structuredCopy(config),
    art: {
      ...structuredCopy(config.art ?? {}),
      entry: "generator/generate.js",
      scriptBytes: scriptBytes.length,
    },
    market: {
      ...structuredCopy(config.market ?? {}),
      mappingCount: Array.isArray(marketMappings.mappings) ? marketMappings.mappings.length : 0,
    },
    hashes: {
      algorithm: HASH_ALGORITHM,
      script: fileHash(scriptBytes),
      dependencies,
      generator: jsonHash(dependencies),
      traitSchema: jsonHash(traitSchema),
      marketMapping: jsonHash(marketMappings),
      metadata: jsonHash(collectionMetadata),
      ...(Object.keys(media).length > 0 ? { media } : {}),
    },
  };

  const integrity = computeIntegrity(manifestWithoutIntegrity, files);
  const manifest = { ...manifestWithoutIntegrity, integrity: { contentHash: integrity.contentHash, projectConfigHash: integrity.projectConfigHash, bundleHash: integrity.bundleHash } };

  const manifestBytes = utf8(stableJsonText(manifest));

  /** @type {Record<string, string>} */
  const checksumFiles = {};
  for (const path of [...files.keys()].sort()) checksumFiles[path] = fileHash(files.get(path));
  checksumFiles["relics.project.json"] = fileHash(manifestBytes);

  const checksums = {
    algorithm: HASH_ALGORITHM,
    files: checksumFiles,
    contentHash: integrity.contentHash,
    projectConfigHash: integrity.projectConfigHash,
    bundleHash: integrity.bundleHash,
  };
  const checksumsBytes = utf8(stableJsonText(checksums));

  const entries = new Map(files);
  entries.set("relics.project.json", manifestBytes);
  entries.set("checksums.json", checksumsBytes);

  const bytes = writeContainer([...entries].map(([path, content]) => ({ path, bytes: content })));
  return { bytes, manifest, checksums, entries };
}

function parseJsonEntry(files, path) {
  try {
    return safeJsonParse(fromUtf8(files.get(path)), { maxDepth: LIMITS.maxJsonDepth, maxNodes: LIMITS.maxJsonNodes });
  } catch (err) {
    throw new BuildError(`${path} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`);
  }
}

/** Deep copy through the canonical serializer, which also refuses anything unserializable. */
function structuredCopy(value) {
  return JSON.parse(canonicalJson(value));
}
