// SPDX-License-Identifier: MIT
// Bundle assembly. Pure: it takes the project's files as bytes and returns the finished container
// bytes. The CLI supplies the filesystem; nothing here touches one, so a server could assemble a
// bundle from an upload with the same code.

import { canonicalJson } from "./canonical-json.js";
import { writeContainer } from "./container.js";
import { fileHash, hashesUnder, computeIntegrity, jsonHash, HASH_ALGORITHM } from "./hashes.js";
import { utf8, fromUtf8 } from "./sha256.js";
import { safeJsonParse } from "./canonical-json.js";
import { LIMITS } from "./limits.js";
import { SCHEMA_VERSION, CREATOR_KIT_VERSION, RUNTIME_VERSION, PROTOCOL_RELEASE_COMPATIBILITY, BUNDLE_STATUSES, magicForStatus } from "./version.js";
import { computeArtBinding, computeBundleCommitment, deriveArtConfig, ArtConfigDerivationError } from "./binding.js";

export class BuildError extends Error {}

/** Paths the builder owns; a project directory must not supply them. */
export const GENERATED_ENTRIES = Object.freeze(["relics.project.json", "checksums.json"]);

/**
 * Deterministic, human-readable JSON text: keys sorted at every level, two-space indent, one
 * trailing newline. Byte-stable across engines, so a file hash of this text is reproducible.
 * @param {unknown} value
 */
export function stableJsonText(value) {
  return `${JSON.stringify(sortDeep(value), null, 2)}\n`;
}

function sortDeep(value) {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value && typeof value === "object") {
    /** @type {Record<string, unknown>} */
    const out = {};
    for (const key of Object.keys(value).sort()) {
      if (value[key] === undefined) continue;
      out[key] = sortDeep(value[key]);
    }
    return out;
  }
  return value;
}

/**
 * @param {{
 *   files: Map<string, Uint8Array>,
 *   config: Record<string, unknown>,
 *   representativeOutputs?: Record<string, string> | null,
 * }} input `files` holds every bundle entry except the two generated ones; `config` is the
 *   creator's project configuration (the manifest without its hashes, binding and integrity
 *   blocks).
 *
 *   `representativeOutputs` maps each seed in `BINDING_SEEDS` to the sha256 of what the generator
 *   drew for it. Assembly is pure and cannot run a sandbox, so the caller that HAS one — the CLI
 *   on export, the web importer on re-export — supplies the digests and the builder commits to
 *   them. Omitting them assembles a bundle whose binding carries no output commitment, which the
 *   validator refuses for a JavaScript project. That refusal is the point: it is what stops a
 *   bundle being assembled by a path that never executed the art.
 * @returns {{ bytes: Uint8Array, manifest: any, checksums: any, entries: Map<string, Uint8Array> }}
 */
export function assembleBundle({ files: inputFiles, config, representativeOutputs = null, canonicalPreviews = null, status = "FINAL" }) {
  if (!(inputFiles instanceof Map)) throw new BuildError("files must be a Map of path -> bytes");

  // FRESH PREVIEWS, NOT WHATEVER SITS IN `previews/`.
  //
  // A creator edits the generator, exports, and ships a bundle whose previews show the OLD art.
  // Nothing about that fails: the previews are just files, and packaging them verbatim is the
  // obvious implementation. It is also a release-integrity defect — the images a reviewer and a
  // marketplace see are not what the generator draws.
  //
  // So when the caller has rendered the art, assembly does not COPY previews, it WRITES them: the
  // canonical bytes for each binding seed replace anything on disk, and any other `previews/*.svg`
  // is dropped rather than carried along unexplained. Callers that cannot render (the migration
  // path, a structural probe) pass null and get the old copy-through, and the validator's
  // PREVIEWS_FRESH check is what refuses the result.
  const files = canonicalPreviews ? applyCanonicalPreviews(inputFiles, canonicalPreviews) : inputFiles;
  for (const generated of GENERATED_ENTRIES) {
    if (files.has(generated)) throw new BuildError(`${generated} is generated by the builder; remove it from the project directory`);
  }
  if (!files.has("generator/generate.js")) throw new BuildError("generator/generate.js is required");
  for (const required of ["traits/schema.json", "market/mappings.json", "metadata/collection.json"]) {
    if (!files.has(required)) throw new BuildError(`${required} is required`);
  }

  const scriptBytes = files.get("generator/generate.js");
  if (scriptBytes.length > LIMITS.maxScriptBytes) {
    throw new BuildError(`generator/generate.js is ${scriptBytes.length} bytes; the public script budget is ${LIMITS.maxScriptBytes}`);
  }

  const dependencies = hashesUnder(files, "generator/");
  const media = hashesUnder(files, "assets/");
  const traitSchema = parseJsonEntry(files, "traits/schema.json");
  const marketMappings = parseJsonEntry(files, "market/mappings.json");
  const collectionMetadata = parseJsonEntry(files, "metadata/collection.json");

  const templateParams = files.has("generator/params.json") ? parseJsonEntry(files, "generator/params.json") : null;

  // THE ART CONFIGURATION, derived from the creator's authoring document rather than accepted from
  // it. `generator/params.json` is what the creator edits and diffs; the bytes below are what the
  // runtime is handed. Encoding them here — inside assembly, from the same files the hashes are
  // taken over — is what makes it impossible for a bundle to carry a configuration its own
  // parameters do not produce.
  const art = deriveArtConfig({ runtime: config.art?.runtime, templateParams, scriptBytes });

  if (!BUNDLE_STATUSES.includes(status)) throw new BuildError(`unknown bundle status ${JSON.stringify(status)}`);
  const magic = magicForStatus(status);

  const manifestWithoutIntegrity = {
    schemaVersion: SCHEMA_VERSION,
    // Committed, because it is inside both integrity hashes. A draft cannot be turned into a final
    // bundle by editing a filename, and cannot be turned into one by editing this field either —
    // that changes contentHash, which changes the commitment.
    status,
    creatorKitVersion: CREATOR_KIT_VERSION,
    runtimeVersion: RUNTIME_VERSION,
    protocolReleaseCompatibility: PROTOCOL_RELEASE_COMPATIBILITY,
    ...structuredCopy(config),
    art: {
      ...structuredCopy(config.art ?? {}),
      entry: "generator/generate.js",
      scriptBytes: scriptBytes.length,
    },
    market: {
      ...structuredCopy(config.market ?? {}),
      mappingCount: Array.isArray(marketMappings.mappings) ? marketMappings.mappings.length : 0,
    },
    hashes: {
      algorithm: HASH_ALGORITHM,
      script: fileHash(scriptBytes),
      dependencies,
      generator: jsonHash(dependencies),
      traitSchema: jsonHash(traitSchema),
      marketMapping: jsonHash(marketMappings),
      metadata: jsonHash(collectionMetadata),
      ...(Object.keys(media).length > 0 ? { media } : {}),
    },
    // Derived, never authored. The block is a pure function of the entries above, so a creator
    // cannot state a binding their files do not support and the validator recomputes it from the
    // container to prove it.
    artBinding: computeArtBinding({
      runtime: config.art?.runtime,
      templateId: config.art?.templateId,
      scriptBytes,
      artConfigBytes: art.bytes,
      artConfigVisualHash: art.visualHash,
      artConfigTraitSchemaHash: art.traitSchemaHash,
      generatorFileHashes: dependencies,
      traitSchema,
      marketMappings,
      collectionMetadata,
      templateParams,
      representativeOutputs,
    }),
  };

  const integrity = computeIntegrity(manifestWithoutIntegrity, files);
  const manifest = {
    ...manifestWithoutIntegrity,
    integrity: {
      contentHash: integrity.contentHash,
      projectConfigHash: integrity.projectConfigHash,
      bundleHash: integrity.bundleHash,
      bundleCommitment: computeBundleCommitment(integrity.projectConfigHash, integrity.contentHash, magic),
    },
  };

  const manifestBytes = utf8(stableJsonText(manifest));

  /** @type {Record<string, string>} */
  const checksumFiles = {};
  for (const path of [...files.keys()].sort()) checksumFiles[path] = fileHash(files.get(path));
  checksumFiles["relics.project.json"] = fileHash(manifestBytes);

  const checksums = {
    algorithm: HASH_ALGORITHM,
    files: checksumFiles,
    contentHash: integrity.contentHash,
    projectConfigHash: integrity.projectConfigHash,
    bundleHash: integrity.bundleHash,
    bundleCommitment: manifest.integrity.bundleCommitment,
  };
  const checksumsBytes = utf8(stableJsonText(checksums));

  const entries = new Map(files);
  entries.set("relics.project.json", manifestBytes);
  entries.set("checksums.json", checksumsBytes);

  const bytes = writeContainer([...entries].map(([path, content]) => ({ path, bytes: content })), { magic });
  return { bytes, manifest, checksums, entries };
}


/**
 * Replaces `previews/seed-*.svg` with the generator's current output.
 * @param {Map<string, Uint8Array>} files
 * @param {Record<string, string>} previews seed -> SVG text
 */
function applyCanonicalPreviews(files, previews) {
  const next = new Map();
  for (const [path, bytes] of files) {
    if (path.startsWith("previews/") && /^previews\/seed-[^/]+\.svg$/.test(path)) continue;
    next.set(path, bytes);
  }
  for (const [seed, svg] of Object.entries(previews)) {
    if (typeof svg !== "string") throw new BuildError(`canonicalPreviews[${seed}] is not SVG text`);
    next.set(`previews/seed-${seed}.svg`, utf8(svg));
  }
  return next;
}

function parseJsonEntry(files, path) {
  try {
    return safeJsonParse(fromUtf8(files.get(path)), { maxDepth: LIMITS.maxJsonDepth, maxNodes: LIMITS.maxJsonNodes });
  } catch (err) {
    throw new BuildError(`${path} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`);
  }
}

/** Deep copy through the canonical serializer, which also refuses anything unserializable. */
function structuredCopy(value) {
  return JSON.parse(canonicalJson(value));
}
